token:
  expiration_time: 86400
  secret: '{cipher}AYBIECLY5j/J9gkGrJSaQWi+rDvbz6wwDYomb9axyektPsjbhGwpUFtQrVaqLbpPZEFKaKgcZExQ+uhJCbVPg8VVKg+THUHeFQzG5C+jSFs7VTm8WeiSBjFS7F5hqrcdVHDeN5Dtg0bBxGdTntaXpBfYhWmRcpzjG7ynKKd6reLqzTSqme1FwnBvVFq1IF023rbbzVE6XY2pa4ubdqtN8ISm4DuHqN2lwobVBS+ODxT7F1/693g3WJNyQVu1L0dWXjogvgTYhyN/GloxWVHotRDnQppz3Dw8AVlJuYWdRA1e/RCfAP6IXP6wOM+nbdCJTpGAoBG4CGsP5u8IffJEPtLEit7SiH2mVVmxlUdBvZ7CPmTCxp43AiX1s79VO70tGF6Kmcvb4IUgsuXfqoQtr6fzxg3gd4YSvPdguCJlPbErbwzhYoaJ0T7tUPAZCj6XmoNNikUfok3g7BqKa1xF6Uj1gAFVvc+Sf4SLQJJObPFFZC+tKlfrvfu0X7La8ytChLTCdl5d7Evs65+Lbq2MYO0mXEA9eppT920Ssknb55Y1XQ=='

gateway:
  ip: 127.0.0.1
