spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password: '{cipher}c5a882a25b480d18ce76a197b4bf66b0501feb90a2432a39d7ced8ba2da54060'

token:
  expiration_time: 86400
  secret: token_ecommerce_changed

gateway:
  ip: 127.0.0.1

